<a href="https://colab.research.google.com/github/ChrisCT17/TareasTHC/blob/main/Actividad_29_de_octubre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [1]:
import numpy as np
a=np.array([1,2,3,4]) #arreglo
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4]


**Arreglos de dimesion 0**

In [2]:
dim_cero=np.array(1) #No tiene corchetes
print(dim_cero) #Los podemos pensar como escalares

1


**Arreglos de dimension 1**

In [3]:
dim_uno=np.array([1,2,3,4]) #Tiene corchetes
print(dim_uno) #Los podemos pensar como vectores

[1 2 3 4]


**Arrglos de dimension 2**

In [4]:
dim_dos = np.array([[1,2,3],[4,5,6]]) #Ambas listas deben de tener el mismo tamaño
print(dim_dos) #Los podemos pensar como matrices
#El numero de listas son las filas de las matrices
#Las columnas son los elementos de la lista

[[1 2 3]
 [4 5 6]]


**Codigos**

In [5]:
print(dim_uno.ndim) #Nos dice el tipo de dimension

1


In [6]:
print(dim_uno.shape)

(4,)


In [7]:
print(dim_dos.shape) #El 2 son las filas y el 3 las coumnas

(2, 3)


In [9]:
A=np.array([[1/2,1,3/4],[2,4,5]])
print(A)

[[0.5  1.   0.75]
 [2.   4.   5.  ]]


In [12]:
import numpy as np
A=np.array([[1,"o"],[0,0]]) #No puede haber mezcla de tipo de datos, marca o un error o convierte todos los elementos al mimsmo tipo
print(A)

[['1' 'o']
 ['0' '0']]


In [16]:
vec=np.array([1,0,-1,4,5])
print(vec[0]) #Esto para acceder a un elemento de la lista, entre corchetes va la posicion del elemento
#Recordemos que python cuenta desde el 0
print(vec[3])
print(vec[-1]) #Nos imprime el ultimo elemento de la lista

1
4
5


In [17]:
print(vec[1:3]) #Esto para imprimir los elementos desde una posicion a otra

[ 0 -1]


In [18]:
n=len(vec) #Nos da la longitud de la lista
print(n)

5


In [20]:
print(vec[1:4])
print(vec[1:5]) #Tenemos que dar la longitud de la lista para que nos imprima el ultimo elemento

[ 0 -1  4]
[ 0 -1  4  5]


In [24]:
vec1=np.array([2,0,-1,4,5,6,7,8,9,10])
print(vec1[1:4])
print(vec1[2:5])
print(vec1[1:10:2]) #imprime los valores de 2 en 2 hasta llegar al ultimo, esto lo indica el ultimo digito que en este caso es el 2

[ 0 -1  4]
[-1  4  5]
[ 0  4  6  8 10]


In [25]:
Mat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(Mat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
#Acceder al 2
print([Mat[0,1]]) #El primer valor indica el numero de lista en este caso es la primera
#El segundo valor indica la posicion del elemento en dicha lista, siempre se cuenta desde el 0

[2]


In [28]:
#Acceder al 11
print(Mat[2,2])

11


In [29]:
#Acceder al 8
print(Mat[1,3])

8


In [30]:
#Acceder al 12
print(Mat[-1,-1])

12


In [ ]:
print(Mat[1,4]) #Esto va a arrojar un error pues la lista solo llega hasta el 3

In [32]:
print(Mat[:,1]) #Nos imprime la columna 1
print(Mat[1,:]) #Nos imprime la fila 1

[ 2  6 10]
[5 6 7 8]


In [33]:
print(Mat[1,1:4])
print(Mat[1:3,2])

[6 7 8]
[ 7 11]


In [36]:
print(Mat[1:3,1:4])#El primero son las filas y el segundo las columnas

[[ 6  7  8]
 [10 11 12]]


In [38]:
print(Mat[0:2,0:3])

[[1 2 3]
 [5 6 7]]


In [40]:
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
print(a+b) #Suma los valores de las listas

[ 5  7  9 11]


In [41]:
Mat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(Mat+Mat)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [62]:
#Producto punto de dos vectores
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
n=len(a)
for i in range(n):
 x=a[i]*b[i]
 print(x)

4
10
18
28
