<a href="https://colab.research.google.com/github/ChrisCT17/TareasTHC/blob/main/Actividad_31_de_octubre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**linspace y reshape**

linspace nos permite dividir un intervalo, el ultimo valor indica la cantidad de puntos en los que sera dividido

In [2]:
import numpy as np #Importamos la libreria
arreglo=np.linspace(0,1,9) #Declaramos el arreglo
arreglo

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

reshape --> modifica dimensiones del arreglo

-> nxn

->n**2 (tamaño del vector)

reshape nos permite hacer matrices

In [7]:
arreglo.reshape((3,3)) #Modificamos las dimensiones del arreglo

array([[0.   , 0.125, 0.25 ],
       [0.375, 0.5  , 0.625],
       [0.75 , 0.875, 1.   ]])

In [10]:
arreglo=np.linspace(0,1,16)
arreglo.reshape((2,8))

array([[0.        , 0.06666667, 0.13333333, 0.2       , 0.26666667,
        0.33333333, 0.4       , 0.46666667],
       [0.53333333, 0.6       , 0.66666667, 0.73333333, 0.8       ,
        0.86666667, 0.93333333, 1.        ]])

In [11]:
arreglo.reshape((16,1)) #vector columna

array([[0.        ],
       [0.06666667],
       [0.13333333],
       [0.2       ],
       [0.26666667],
       [0.33333333],
       [0.4       ],
       [0.46666667],
       [0.53333333],
       [0.6       ],
       [0.66666667],
       [0.73333333],
       [0.8       ],
       [0.86666667],
       [0.93333333],
       [1.        ]])

In [12]:
#Lo anterior es equivalente a poner:
arreglo.reshape((-1,1)) #es mas general pues no necestiramos conocer la cantidad de puntos que tenemos

array([[0.        ],
       [0.06666667],
       [0.13333333],
       [0.2       ],
       [0.26666667],
       [0.33333333],
       [0.4       ],
       [0.46666667],
       [0.53333333],
       [0.6       ],
       [0.66666667],
       [0.73333333],
       [0.8       ],
       [0.86666667],
       [0.93333333],
       [1.        ]])

#**Comparativos**

In [14]:
arr=np.array([2,5,1,8,9,10,15,4,6])
MB=arr>5 #Nos devuelve un arreglo de booleanos, se le conoce como mascara buleana
print(MB)

[False False False  True  True  True  True False  True]


In [15]:
arr[MB] #Nos devuelve los valores que cumplen la condicion
print(arr[MB])

[ 8  9 10 15  6]


In [16]:
arr[arr==2] #Nos devuelve los valores que son iguales a 2

array([2])

In [17]:
arr[arr%2==0] #Nos devuelve los valores que son pares o divisbles entre dos

array([ 2,  8, 10,  4,  6])

In [19]:
#arr[(arr<10) and (arr>5)]
#Esto tiene errores, pues no sabe la funcion cual elegir

In [23]:
#arr1=arr[(arr<10)]
#arr1[(arr1>5)] #Esto es una manera correcta de escribir lo anterior
#Hay que tener cuidado con esto, pues ya no podremos utlizar los valores completos

In [25]:
#Para solucionar ese inconveniente hacemos:
arr=np.array([2,5,1,8,9,10,15,4,6])
arr1=np.copy(arr)
arr1=arr1[(arr1<10)]
arr1[(arr1>5)]

array([8, 9, 6])

# **Where**

In [26]:
arr=np.array([2,5,1,8,9,10,15,4,6])
arr2=np.where(arr%2==0) #Nos devuelve los indices de los valores que cumplen la condicion
arr2

(array([0, 3, 5, 7, 8]),)

In [27]:
arr[arr2] #Nos devuelve los valores que cumplen la condicion

array([ 2,  8, 10,  4,  6])

#**searchsorted**

In [28]:
arr

array([ 2,  5,  1,  8,  9, 10, 15,  4,  6])

In [29]:
arr=np.sort(arr) #Ordenamos el arreglo
arr

array([ 1,  2,  4,  5,  6,  8,  9, 10, 15])

In [30]:
index=np.searchsorted(arr,6) #Nos devuelve el indice donde deberia ir el valor 7
index #No funciona si e arreglo no esta ordenado

4

#**Comandos de utilidad**

In [31]:
np.mean(arr) #Nos devuelve el promedio del arreglo

6.666666666666667

In [33]:
np.median(arr) #Nos devuelve la mediana del arreglo

6.0

In [32]:
np.sum(arr) #Nos devuelve la suma del arreglo

60

In [34]:
np.sqrt(arr) #Nos devuelve la raiz cuadrada de cada valor del arreglo

array([1.        , 1.41421356, 2.        , 2.23606798, 2.44948974,
       2.82842712, 3.        , 3.16227766, 3.87298335])

#**Operaciones con arreglos**

In [35]:
arr+arr #Nos devuelve la suma de los arreglos

array([ 2,  4,  8, 10, 12, 16, 18, 20, 30])

In [38]:
arr**2 #Nos devuelve el cuadrado de cada valor del arreglo

array([  1,   4,  16,  25,  36,  64,  81, 100, 225])

In [36]:
arr*arr #Nos devuelve la multiplicacion de los arreglos

array([  1,   4,  16,  25,  36,  64,  81, 100, 225])

In [37]:
np.dot(arr,arr) #Nos devuelve el producto punto de los arreglos

552

In [40]:
arr/arr #Nos devuelve la division de los arreglos

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
arr-arr #Nos devuelve la resta de los arreglos

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

#**Problema de calentamiento**

De un arreglo que seleccione aquellos impares

In [42]:
vector=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
vector[vector%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13])

Dados a,b pertenecientes a los reales a la n, programe a*b (producto escalar)

In [53]:
#Version chafita
def producto_escalar1(a,b):
  a=input("Ingrese el primer vector: ")
  b=input("Ingrese el segundo vector: ")
  a=a.split(",")
  b=b.split(",")
  producto_escalar=0.0
  for i in range(len(a)):
    a[i]=float(a[i])
  for i in range(len(b)):
    b[i]=float(b[i])
  for i in range(len(a)):
    producto_escalar=producto_escalar+a[i]*b[i]
  return producto_escalar
producto_escalar1(a,b)

Ingrese el primer vector: 1,2,3
Ingrese el segundo vector: 2,3,4


20.0

In [62]:
#Version completa
def producto_punto(a,b):
  while True:
    try:
      a=input("Ingrese el primer vector: ")
      b=input("Ingrese el segundo vector: ")
      a=a.split(",")
      b=b.split(",")
      if len(a)!=len(b):
        print("Los vectores no son del mismo tamaño")
        continue
      else:
        for i in range(len(a)):
          a[i]=float(a[i])
        for i in range(len(b)):
          b[i]=float(b[i])
        producto_escalar=0.0
        for i in range(len(a)):
          producto_escalar=producto_escalar+a[i]*b[i]
        print("El producto punto (escalar) es: ", producto_escalar)
        break
    except ValueError:
      print("Los valores ingresados no son validos")
      continue
producto_punto(a,b)


Ingrese el primer vector: 1,2,3
Ingrese el segundo vector: 2,3,4
El producto punto (escalar) es:  20.0


Ejercicio: Programar una multiplicacion de una matriz con un vector

In [83]:
def MatVec(A,b):
  A= np.array([[1.,1.,1.],[1.,1.,1.],[1.,1.,1.]])
  b= np.array([1,2,3])
  x=np.zeros(len(b))
  producto_escalar=0.0
  for i in range(len(A)):
    for j in range(len(b)):
      producto_escalar=producto_escalar+A[i,j]*b[j]
    x[i]=producto_escalar
    producto_escalar=0.0
  return x
MatVec(1,2)


array([6., 6., 6.])